//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Client.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.Client.Contracts.Properties.ObjectResources", typeof(ObjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products_TypeDisplayName {
            get {
                return ResourceManager.GetString("Products_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Products_Id {
            get {
                return ResourceManager.GetString("Products_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Products_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Products_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Products_ProductName {
            get {
                return ResourceManager.GetString("Products_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Products_ProductName_RequiredMsg {
            get {
                return ResourceManager.GetString("Products_ProductName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Products_SupplierID {
            get {
                return ResourceManager.GetString("Products_SupplierID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Products_CategoryID {
            get {
                return ResourceManager.GetString("Products_CategoryID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string Products_QuantityPerUnit {
            get {
                return ResourceManager.GetString("Products_QuantityPerUnit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Products_UnitPrice {
            get {
                return ResourceManager.GetString("Products_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string Products_UnitsInStock {
            get {
                return ResourceManager.GetString("Products_UnitsInStock", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string Products_UnitsOnOrder {
            get {
                return ResourceManager.GetString("Products_UnitsOnOrder", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string Products_ReorderLevel {
            get {
                return ResourceManager.GetString("Products_ReorderLevel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Products_Discontinued {
            get {
                return ResourceManager.GetString("Products_Discontinued", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Products_Discontinued_RequiredMsg {
            get {
                return ResourceManager.GetString("Products_Discontinued_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Products_Categories {
            get {
                return ResourceManager.GetString("Products_Categories", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Products_Suppliers {
            get {
                return ResourceManager.GetString("Products_Suppliers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer customer demo.
        /// </summary>
        public static string CustomerCustomerDemo_TypeDisplayName {
            get {
                return ResourceManager.GetString("CustomerCustomerDemo_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer id.
        /// </summary>
        public static string CustomerCustomerDemo_CustomerID {
            get {
                return ResourceManager.GetString("CustomerCustomerDemo_CustomerID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CustomerCustomerDemo_CustomerID_RequiredMsg {
            get {
                return ResourceManager.GetString("CustomerCustomerDemo_CustomerID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer type id.
        /// </summary>
        public static string CustomerCustomerDemo_CustomerTypeID {
            get {
                return ResourceManager.GetString("CustomerCustomerDemo_CustomerTypeID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CustomerCustomerDemo_CustomerTypeID_RequiredMsg {
            get {
                return ResourceManager.GetString("CustomerCustomerDemo_CustomerTypeID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerDemographic.
        /// </summary>
        public static string CustomerCustomerDemo_CustomerDemographic {
            get {
                return ResourceManager.GetString("CustomerCustomerDemo_CustomerDemographic", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string CustomerCustomerDemo_Customers {
            get {
                return ResourceManager.GetString("CustomerCustomerDemo_Customers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password token.
        /// </summary>
        public static string SysResetPasswordToken_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysResetPasswordToken_Id {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string SysResetPasswordToken_UserId {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_UserId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string SysResetPasswordToken_Token {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Token", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Token_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Token_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string SysResetPasswordToken_ValidFrom {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_ValidFrom", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_ValidFrom_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_ValidFrom_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is executed.
        /// </summary>
        public static string SysResetPasswordToken_IsExecuted {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_IsExecuted", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_IsExecuted_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_IsExecuted_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysUser.
        /// </summary>
        public static string SysResetPasswordToken_SysUser {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_SysUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string SysRole_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysRole_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysRole_Id {
            get {
                return ResourceManager.GetString("SysRole_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SysRole_Name {
            get {
                return ResourceManager.GetString("SysRole_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SysRole_Description {
            get {
                return ResourceManager.GetString("SysRole_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Owner user id.
        /// </summary>
        public static string SysRole_OwnerUserID {
            get {
                return ResourceManager.GetString("SysRole_OwnerUserID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is own by user.
        /// </summary>
        public static string SysRole_IsOwnByUser {
            get {
                return ResourceManager.GetString("SysRole_IsOwnByUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsOwnByUser_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsOwnByUser_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OwnerUser.
        /// </summary>
        public static string SysRole_OwnerUser {
            get {
                return ResourceManager.GetString("SysRole_OwnerUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is system.
        /// </summary>
        public static string SysRole_IsSystem {
            get {
                return ResourceManager.GetString("SysRole_IsSystem", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsSystem_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsSystem_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysRolePermissions.
        /// </summary>
        public static string SysRole_SysRolePermissions {
            get {
                return ResourceManager.GetString("SysRole_SysRolePermissions", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        public static string Territory_TypeDisplayName {
            get {
                return ResourceManager.GetString("Territory_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Territory id.
        /// </summary>
        public static string Territory_Id {
            get {
                return ResourceManager.GetString("Territory_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Territory_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Territory_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Territory description.
        /// </summary>
        public static string Territory_TerritoryDescription {
            get {
                return ResourceManager.GetString("Territory_TerritoryDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Territory_TerritoryDescription_RequiredMsg {
            get {
                return ResourceManager.GetString("Territory_TerritoryDescription_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region id.
        /// </summary>
        public static string Territory_RegionID {
            get {
                return ResourceManager.GetString("Territory_RegionID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Territory_RegionID_RequiredMsg {
            get {
                return ResourceManager.GetString("Territory_RegionID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Territory_Region {
            get {
                return ResourceManager.GetString("Territory_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee territory.
        /// </summary>
        public static string EmployeeTerritory_TypeDisplayName {
            get {
                return ResourceManager.GetString("EmployeeTerritory_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee id.
        /// </summary>
        public static string EmployeeTerritory_EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeTerritory_EmployeeID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmployeeTerritory_EmployeeID_RequiredMsg {
            get {
                return ResourceManager.GetString("EmployeeTerritory_EmployeeID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Territory id.
        /// </summary>
        public static string EmployeeTerritory_TerritoryID {
            get {
                return ResourceManager.GetString("EmployeeTerritory_TerritoryID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmployeeTerritory_TerritoryID_RequiredMsg {
            get {
                return ResourceManager.GetString("EmployeeTerritory_TerritoryID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeeTerritory_Employees {
            get {
                return ResourceManager.GetString("EmployeeTerritory_Employees", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        public static string EmployeeTerritory_Territory {
            get {
                return ResourceManager.GetString("EmployeeTerritory_Territory", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers_TypeDisplayName {
            get {
                return ResourceManager.GetString("Customers_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Customers_Id {
            get {
                return ResourceManager.GetString("Customers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Customers_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Customers_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Customers_CompanyName {
            get {
                return ResourceManager.GetString("Customers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Customers_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Customers_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Customers_ContactName {
            get {
                return ResourceManager.GetString("Customers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Customers_ContactTitle {
            get {
                return ResourceManager.GetString("Customers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Customers_Address {
            get {
                return ResourceManager.GetString("Customers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Customers_City {
            get {
                return ResourceManager.GetString("Customers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Customers_Region {
            get {
                return ResourceManager.GetString("Customers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Customers_PostalCode {
            get {
                return ResourceManager.GetString("Customers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Customers_Country {
            get {
                return ResourceManager.GetString("Customers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Customers_Phone {
            get {
                return ResourceManager.GetString("Customers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Customers_Fax {
            get {
                return ResourceManager.GetString("Customers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories_TypeDisplayName {
            get {
                return ResourceManager.GetString("Categories_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Categories_Id {
            get {
                return ResourceManager.GetString("Categories_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Categories_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Categories_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Categories_CategoryName {
            get {
                return ResourceManager.GetString("Categories_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Categories_CategoryName_RequiredMsg {
            get {
                return ResourceManager.GetString("Categories_CategoryName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Categories_Description {
            get {
                return ResourceManager.GetString("Categories_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Categories_Picture {
            get {
                return ResourceManager.GetString("Categories_Picture", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region_TypeDisplayName {
            get {
                return ResourceManager.GetString("Region_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region id.
        /// </summary>
        public static string Region_Id {
            get {
                return ResourceManager.GetString("Region_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Region_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Region_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region description.
        /// </summary>
        public static string Region_RegionDescription {
            get {
                return ResourceManager.GetString("Region_RegionDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Region_RegionDescription_RequiredMsg {
            get {
                return ResourceManager.GetString("Region_RegionDescription_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers_TypeDisplayName {
            get {
                return ResourceManager.GetString("Suppliers_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Suppliers_Id {
            get {
                return ResourceManager.GetString("Suppliers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Suppliers_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Suppliers_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Suppliers_CompanyName {
            get {
                return ResourceManager.GetString("Suppliers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Suppliers_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Suppliers_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Suppliers_ContactName {
            get {
                return ResourceManager.GetString("Suppliers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Suppliers_ContactTitle {
            get {
                return ResourceManager.GetString("Suppliers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Suppliers_Address {
            get {
                return ResourceManager.GetString("Suppliers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Suppliers_City {
            get {
                return ResourceManager.GetString("Suppliers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Suppliers_Region {
            get {
                return ResourceManager.GetString("Suppliers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Suppliers_PostalCode {
            get {
                return ResourceManager.GetString("Suppliers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Suppliers_Country {
            get {
                return ResourceManager.GetString("Suppliers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Suppliers_Phone {
            get {
                return ResourceManager.GetString("Suppliers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Suppliers_Fax {
            get {
                return ResourceManager.GetString("Suppliers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Suppliers_HomePage {
            get {
                return ResourceManager.GetString("Suppliers_HomePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Operation lock.
        /// </summary>
        public static string SysOperationLock_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysOperationLock_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name.
        /// </summary>
        public static string SysOperationLock_OperationName {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Operation context.
        /// </summary>
        public static string SysOperationLock_OperationContext {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationContext", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationContext_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationContext_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string SysOperationLock_UserId {
            get {
                return ResourceManager.GetString("SysOperationLock_UserId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Machine name.
        /// </summary>
        public static string SysOperationLock_MachineName {
            get {
                return ResourceManager.GetString("SysOperationLock_MachineName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Process id.
        /// </summary>
        public static string SysOperationLock_ProcessId {
            get {
                return ResourceManager.GetString("SysOperationLock_ProcessId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Aquired time.
        /// </summary>
        public static string SysOperationLock_AquiredTime {
            get {
                return ResourceManager.GetString("SysOperationLock_AquiredTime", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_AquiredTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_AquiredTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration time.
        /// </summary>
        public static string SysOperationLock_ExpirationTime {
            get {
                return ResourceManager.GetString("SysOperationLock_ExpirationTime", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_ExpirationTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_ExpirationTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysUser.
        /// </summary>
        public static string SysOperationLock_SysUser {
            get {
                return ResourceManager.GetString("SysOperationLock_SysUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders_TypeDisplayName {
            get {
                return ResourceManager.GetString("Orders_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string Orders_Id {
            get {
                return ResourceManager.GetString("Orders_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Orders_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Orders_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Company Name.
        /// </summary>
        public static string Orders_CustomerID {
            get {
                return ResourceManager.GetString("Orders_CustomerID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Orders_CustomerID_RequiredMsg {
            get {
                return ResourceManager.GetString("Orders_CustomerID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Orders_EmployeeID {
            get {
                return ResourceManager.GetString("Orders_EmployeeID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Orders_OrderDate {
            get {
                return ResourceManager.GetString("Orders_OrderDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string Orders_RequiredDate {
            get {
                return ResourceManager.GetString("Orders_RequiredDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Orders_ShippedDate {
            get {
                return ResourceManager.GetString("Orders_ShippedDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Company Name.
        /// </summary>
        public static string Orders_ShipVia {
            get {
                return ResourceManager.GetString("Orders_ShipVia", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Orders_Freight {
            get {
                return ResourceManager.GetString("Orders_Freight", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string Orders_ShipName {
            get {
                return ResourceManager.GetString("Orders_ShipName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Orders_ShipAddress {
            get {
                return ResourceManager.GetString("Orders_ShipAddress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string Orders_ShipCity {
            get {
                return ResourceManager.GetString("Orders_ShipCity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string Orders_ShipRegion {
            get {
                return ResourceManager.GetString("Orders_ShipRegion", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string Orders_ShipPostalCode {
            get {
                return ResourceManager.GetString("Orders_ShipPostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string Orders_ShipCountry {
            get {
                return ResourceManager.GetString("Orders_ShipCountry", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Orders_Customers {
            get {
                return ResourceManager.GetString("Orders_Customers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Orders_Employees {
            get {
                return ResourceManager.GetString("Orders_Employees", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        public static string Orders_Shippers {
            get {
                return ResourceManager.GetString("Orders_Shippers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetails.
        /// </summary>
        public static string Orders_OrderDetails {
            get {
                return ResourceManager.GetString("Orders_OrderDetails", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetails.
        /// </summary>
        public static string OrderDetails_TypeDisplayName {
            get {
                return ResourceManager.GetString("OrderDetails_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID.
        /// </summary>
        public static string OrderDetails_OrderID {
            get {
                return ResourceManager.GetString("OrderDetails_OrderID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetails_OrderID_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetails_OrderID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string OrderDetails_ProductID {
            get {
                return ResourceManager.GetString("OrderDetails_ProductID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetails_ProductID_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetails_ProductID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string OrderDetails_UnitPrice {
            get {
                return ResourceManager.GetString("OrderDetails_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetails_UnitPrice_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetails_UnitPrice_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderDetails_Quantity {
            get {
                return ResourceManager.GetString("OrderDetails_Quantity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetails_Quantity_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetails_Quantity_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discount, %.
        /// </summary>
        public static string OrderDetails_Discount {
            get {
                return ResourceManager.GetString("OrderDetails_Discount", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetails_Discount_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetails_Discount_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrderDetails_Orders {
            get {
                return ResourceManager.GetString("OrderDetails_Orders", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string OrderDetails_Products {
            get {
                return ResourceManager.GetString("OrderDetails_Products", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SysSetting_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysSetting_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysSetting_Id {
            get {
                return ResourceManager.GetString("SysSetting_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property id.
        /// </summary>
        public static string SysSetting_SettingPropertyId {
            get {
                return ResourceManager.GetString("SysSetting_SettingPropertyId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_SettingPropertyId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_SettingPropertyId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string SysSetting_UserId {
            get {
                return ResourceManager.GetString("SysSetting_UserId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to StringValue.
        /// </summary>
        public static string SysSetting_StringValue {
            get {
                return ResourceManager.GetString("SysSetting_StringValue", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysSettingProperty.
        /// </summary>
        public static string SysSetting_SysSettingProperty {
            get {
                return ResourceManager.GetString("SysSetting_SysSettingProperty", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysUser.
        /// </summary>
        public static string SysSetting_SysUser {
            get {
                return ResourceManager.GetString("SysSetting_SysUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees_TypeDisplayName {
            get {
                return ResourceManager.GetString("Employees_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Employees_Id {
            get {
                return ResourceManager.GetString("Employees_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employees_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Employees_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Employees_LastName {
            get {
                return ResourceManager.GetString("Employees_LastName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employees_LastName_RequiredMsg {
            get {
                return ResourceManager.GetString("Employees_LastName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Employees_FirstName {
            get {
                return ResourceManager.GetString("Employees_FirstName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employees_FirstName_RequiredMsg {
            get {
                return ResourceManager.GetString("Employees_FirstName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Employees_Title {
            get {
                return ResourceManager.GetString("Employees_Title", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title Of Courtesy.
        /// </summary>
        public static string Employees_TitleOfCourtesy {
            get {
                return ResourceManager.GetString("Employees_TitleOfCourtesy", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Employees_BirthDate {
            get {
                return ResourceManager.GetString("Employees_BirthDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string Employees_HireDate {
            get {
                return ResourceManager.GetString("Employees_HireDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Employees_Address {
            get {
                return ResourceManager.GetString("Employees_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Employees_City {
            get {
                return ResourceManager.GetString("Employees_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Employees_Region {
            get {
                return ResourceManager.GetString("Employees_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Employees_PostalCode {
            get {
                return ResourceManager.GetString("Employees_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Employees_Country {
            get {
                return ResourceManager.GetString("Employees_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Employees_HomePhone {
            get {
                return ResourceManager.GetString("Employees_HomePhone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Employees_Extension {
            get {
                return ResourceManager.GetString("Employees_Extension", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Employees_Photo {
            get {
                return ResourceManager.GetString("Employees_Photo", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Employees_Notes {
            get {
                return ResourceManager.GetString("Employees_Notes", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reports To.
        /// </summary>
        public static string Employees_ReportsTo {
            get {
                return ResourceManager.GetString("Employees_ReportsTo", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Path.
        /// </summary>
        public static string Employees_PhotoPath {
            get {
                return ResourceManager.GetString("Employees_PhotoPath", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to ReportsToEmployees.
        /// </summary>
        public static string Employees_ReportsToEmployees {
            get {
                return ResourceManager.GetString("Employees_ReportsToEmployees", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Document scan file.
        /// </summary>
        public static string Employees_DocumentScanFileId {
            get {
                return ResourceManager.GetString("Employees_DocumentScanFileId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer demographic.
        /// </summary>
        public static string CustomerDemographic_TypeDisplayName {
            get {
                return ResourceManager.GetString("CustomerDemographic_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer type id.
        /// </summary>
        public static string CustomerDemographic_Id {
            get {
                return ResourceManager.GetString("CustomerDemographic_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CustomerDemographic_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CustomerDemographic_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer desc.
        /// </summary>
        public static string CustomerDemographic_CustomerDesc {
            get {
                return ResourceManager.GetString("CustomerDemographic_CustomerDesc", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property.
        /// </summary>
        public static string SysSettingProperty_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysSettingProperty_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysSettingProperty_Id {
            get {
                return ResourceManager.GetString("SysSettingProperty_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SysSettingProperty_Name {
            get {
                return ResourceManager.GetString("SysSettingProperty_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is managed.
        /// </summary>
        public static string SysSettingProperty_IsManaged {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsManaged", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsManaged_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsManaged_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SysSettingProperty_Description {
            get {
                return ResourceManager.GetString("SysSettingProperty_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ui editor type.
        /// </summary>
        public static string SysSettingProperty_UIEditorType {
            get {
                return ResourceManager.GetString("SysSettingProperty_UIEditorType", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string SysSettingProperty_GroupName {
            get {
                return ResourceManager.GetString("SysSettingProperty_GroupName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is overridable.
        /// </summary>
        public static string SysSettingProperty_IsOverridable {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsOverridable", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsOverridable_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsOverridable_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Default type.
        /// </summary>
        public static string SysSettingProperty_DefaultType {
            get {
                return ResourceManager.GetString("SysSettingProperty_DefaultType", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        public static string Shippers_TypeDisplayName {
            get {
                return ResourceManager.GetString("Shippers_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Shippers_Id {
            get {
                return ResourceManager.GetString("Shippers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Shippers_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Shippers_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Shippers_CompanyName {
            get {
                return ResourceManager.GetString("Shippers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Shippers_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Shippers_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Shippers_Phone {
            get {
                return ResourceManager.GetString("Shippers_Phone", resourceCulture);
            }
		}
        
        
    }
}