//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Client.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Client.Contracts.Properties.ObjectResources", typeof(ObjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status.
        /// </summary>
        public static string OrderStatus_TypeDisplayName {
            get {
                return ResourceManager.GetString("OrderStatus_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string OrderStatus_Id {
            get {
                return ResourceManager.GetString("OrderStatus_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OrderStatus_Name {
            get {
                return ResourceManager.GetString("OrderStatus_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product_TypeDisplayName {
            get {
                return ResourceManager.GetString("Product_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product_Id {
            get {
                return ResourceManager.GetString("Product_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Product_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Product_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product_ProductName {
            get {
                return ResourceManager.GetString("Product_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Product_ProductName_RequiredMsg {
            get {
                return ResourceManager.GetString("Product_ProductName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Product_SupplierID {
            get {
                return ResourceManager.GetString("Product_SupplierID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Product_CategoryID {
            get {
                return ResourceManager.GetString("Product_CategoryID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string Product_QuantityPerUnit {
            get {
                return ResourceManager.GetString("Product_QuantityPerUnit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Product_UnitPrice {
            get {
                return ResourceManager.GetString("Product_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string Product_UnitsInStock {
            get {
                return ResourceManager.GetString("Product_UnitsInStock", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string Product_UnitsOnOrder {
            get {
                return ResourceManager.GetString("Product_UnitsOnOrder", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string Product_ReorderLevel {
            get {
                return ResourceManager.GetString("Product_ReorderLevel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Product_Discontinued {
            get {
                return ResourceManager.GetString("Product_Discontinued", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Product_Discontinued_RequiredMsg {
            get {
                return ResourceManager.GetString("Product_Discontinued_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Product_Categories {
            get {
                return ResourceManager.GetString("Product_Categories", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Product_Suppliers {
            get {
                return ResourceManager.GetString("Product_Suppliers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password token.
        /// </summary>
        public static string SysResetPasswordToken_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysResetPasswordToken_Id {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string SysResetPasswordToken_UserId {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_UserId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string SysResetPasswordToken_Token {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Token", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Token_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Token_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string SysResetPasswordToken_ValidFrom {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_ValidFrom", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_ValidFrom_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_ValidFrom_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is executed.
        /// </summary>
        public static string SysResetPasswordToken_IsExecuted {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_IsExecuted", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_IsExecuted_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_IsExecuted_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysUser.
        /// </summary>
        public static string SysResetPasswordToken_SysUser {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_SysUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string SysRole_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysRole_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysRole_Id {
            get {
                return ResourceManager.GetString("SysRole_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SysRole_Name {
            get {
                return ResourceManager.GetString("SysRole_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SysRole_Description {
            get {
                return ResourceManager.GetString("SysRole_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Owner user id.
        /// </summary>
        public static string SysRole_OwnerUserID {
            get {
                return ResourceManager.GetString("SysRole_OwnerUserID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is own by user.
        /// </summary>
        public static string SysRole_IsOwnByUser {
            get {
                return ResourceManager.GetString("SysRole_IsOwnByUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsOwnByUser_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsOwnByUser_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OwnerUser.
        /// </summary>
        public static string SysRole_OwnerUser {
            get {
                return ResourceManager.GetString("SysRole_OwnerUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is system.
        /// </summary>
        public static string SysRole_IsSystem {
            get {
                return ResourceManager.GetString("SysRole_IsSystem", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsSystem_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsSystem_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysRolePermissions.
        /// </summary>
        public static string SysRole_SysRolePermissions {
            get {
                return ResourceManager.GetString("SysRole_SysRolePermissions", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer_TypeDisplayName {
            get {
                return ResourceManager.GetString("Customer_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Customer_Id {
            get {
                return ResourceManager.GetString("Customer_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Customer_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Customer_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Customer_CompanyName {
            get {
                return ResourceManager.GetString("Customer_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Customer_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Customer_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Customer_ContactName {
            get {
                return ResourceManager.GetString("Customer_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Customer_ContactTitle {
            get {
                return ResourceManager.GetString("Customer_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Customer_City {
            get {
                return ResourceManager.GetString("Customer_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Customer_Region {
            get {
                return ResourceManager.GetString("Customer_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Customer_PostalCode {
            get {
                return ResourceManager.GetString("Customer_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Customer_Country {
            get {
                return ResourceManager.GetString("Customer_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Customer_Phone {
            get {
                return ResourceManager.GetString("Customer_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Customer_Fax {
            get {
                return ResourceManager.GetString("Customer_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category_TypeDisplayName {
            get {
                return ResourceManager.GetString("Category_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Category_Id {
            get {
                return ResourceManager.GetString("Category_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Category_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Category_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Category_CategoryName {
            get {
                return ResourceManager.GetString("Category_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Category_CategoryName_RequiredMsg {
            get {
                return ResourceManager.GetString("Category_CategoryName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Category_Picture {
            get {
                return ResourceManager.GetString("Category_Picture", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier_TypeDisplayName {
            get {
                return ResourceManager.GetString("Supplier_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Supplier_Id {
            get {
                return ResourceManager.GetString("Supplier_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Supplier_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Supplier_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Supplier_CompanyName {
            get {
                return ResourceManager.GetString("Supplier_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Supplier_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Supplier_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Supplier_ContactName {
            get {
                return ResourceManager.GetString("Supplier_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Supplier_ContactTitle {
            get {
                return ResourceManager.GetString("Supplier_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Supplier_Address {
            get {
                return ResourceManager.GetString("Supplier_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Supplier_City {
            get {
                return ResourceManager.GetString("Supplier_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Supplier_Region {
            get {
                return ResourceManager.GetString("Supplier_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Supplier_PostalCode {
            get {
                return ResourceManager.GetString("Supplier_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Supplier_Country {
            get {
                return ResourceManager.GetString("Supplier_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Supplier_Phone {
            get {
                return ResourceManager.GetString("Supplier_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Supplier_Fax {
            get {
                return ResourceManager.GetString("Supplier_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Supplier_HomePage {
            get {
                return ResourceManager.GetString("Supplier_HomePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Operation lock.
        /// </summary>
        public static string SysOperationLock_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysOperationLock_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name.
        /// </summary>
        public static string SysOperationLock_OperationName {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Operation context.
        /// </summary>
        public static string SysOperationLock_OperationContext {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationContext", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationContext_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationContext_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string SysOperationLock_UserId {
            get {
                return ResourceManager.GetString("SysOperationLock_UserId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Machine name.
        /// </summary>
        public static string SysOperationLock_MachineName {
            get {
                return ResourceManager.GetString("SysOperationLock_MachineName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Process id.
        /// </summary>
        public static string SysOperationLock_ProcessId {
            get {
                return ResourceManager.GetString("SysOperationLock_ProcessId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Aquired time.
        /// </summary>
        public static string SysOperationLock_AquiredTime {
            get {
                return ResourceManager.GetString("SysOperationLock_AquiredTime", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_AquiredTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_AquiredTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration time.
        /// </summary>
        public static string SysOperationLock_ExpirationTime {
            get {
                return ResourceManager.GetString("SysOperationLock_ExpirationTime", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_ExpirationTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_ExpirationTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysUser.
        /// </summary>
        public static string SysOperationLock_SysUser {
            get {
                return ResourceManager.GetString("SysOperationLock_SysUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order_TypeDisplayName {
            get {
                return ResourceManager.GetString("Order_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string Order_Id {
            get {
                return ResourceManager.GetString("Order_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Order_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Order_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Company Name.
        /// </summary>
        public static string Order_CustomerID {
            get {
                return ResourceManager.GetString("Order_CustomerID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Order_EmployeeID {
            get {
                return ResourceManager.GetString("Order_EmployeeID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Order_OrderDate {
            get {
                return ResourceManager.GetString("Order_OrderDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string Order_RequiredDate {
            get {
                return ResourceManager.GetString("Order_RequiredDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Order_ShippedDate {
            get {
                return ResourceManager.GetString("Order_ShippedDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Company Name.
        /// </summary>
        public static string Order_ShipVia {
            get {
                return ResourceManager.GetString("Order_ShipVia", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Order_Freight {
            get {
                return ResourceManager.GetString("Order_Freight", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string Order_ShipName {
            get {
                return ResourceManager.GetString("Order_ShipName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Order_ShipAddress {
            get {
                return ResourceManager.GetString("Order_ShipAddress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string Order_ShipCity {
            get {
                return ResourceManager.GetString("Order_ShipCity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string Order_ShipRegion {
            get {
                return ResourceManager.GetString("Order_ShipRegion", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string Order_ShipPostalCode {
            get {
                return ResourceManager.GetString("Order_ShipPostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string Order_ShipCountry {
            get {
                return ResourceManager.GetString("Order_ShipCountry", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Order_Customers {
            get {
                return ResourceManager.GetString("Order_Customers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Order_Employees {
            get {
                return ResourceManager.GetString("Order_Employees", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        public static string Order_Shippers {
            get {
                return ResourceManager.GetString("Order_Shippers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDetailss.
        /// </summary>
        public static string Order_OrderDetailss {
            get {
                return ResourceManager.GetString("Order_OrderDetailss", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Order_StatusID {
            get {
                return ResourceManager.GetString("Order_StatusID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderStatus.
        /// </summary>
        public static string Order_OrderStatus {
            get {
                return ResourceManager.GetString("Order_OrderStatus", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order detail.
        /// </summary>
        public static string OrderDetail_TypeDisplayName {
            get {
                return ResourceManager.GetString("OrderDetail_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string OrderDetail_Id {
            get {
                return ResourceManager.GetString("OrderDetail_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID.
        /// </summary>
        public static string OrderDetail_OrderID {
            get {
                return ResourceManager.GetString("OrderDetail_OrderID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_OrderID_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_OrderID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string OrderDetail_ProductID {
            get {
                return ResourceManager.GetString("OrderDetail_ProductID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_ProductID_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_ProductID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string OrderDetail_UnitPrice {
            get {
                return ResourceManager.GetString("OrderDetail_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_UnitPrice_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_UnitPrice_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderDetail_Quantity {
            get {
                return ResourceManager.GetString("OrderDetail_Quantity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_Quantity_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_Quantity_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discount, %.
        /// </summary>
        public static string OrderDetail_Discount {
            get {
                return ResourceManager.GetString("OrderDetail_Discount", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_Discount_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_Discount_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrderDetail_Orders {
            get {
                return ResourceManager.GetString("OrderDetail_Orders", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string OrderDetail_Products {
            get {
                return ResourceManager.GetString("OrderDetail_Products", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SysSetting_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysSetting_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysSetting_Id {
            get {
                return ResourceManager.GetString("SysSetting_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property id.
        /// </summary>
        public static string SysSetting_SettingPropertyId {
            get {
                return ResourceManager.GetString("SysSetting_SettingPropertyId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_SettingPropertyId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_SettingPropertyId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string SysSetting_UserId {
            get {
                return ResourceManager.GetString("SysSetting_UserId", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to StringValue.
        /// </summary>
        public static string SysSetting_StringValue {
            get {
                return ResourceManager.GetString("SysSetting_StringValue", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysSettingProperty.
        /// </summary>
        public static string SysSetting_SysSettingProperty {
            get {
                return ResourceManager.GetString("SysSetting_SysSettingProperty", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to SysUser.
        /// </summary>
        public static string SysSetting_SysUser {
            get {
                return ResourceManager.GetString("SysSetting_SysUser", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee_TypeDisplayName {
            get {
                return ResourceManager.GetString("Employee_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Employee_Id {
            get {
                return ResourceManager.GetString("Employee_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employee_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Employee_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Employee_LastName {
            get {
                return ResourceManager.GetString("Employee_LastName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employee_LastName_RequiredMsg {
            get {
                return ResourceManager.GetString("Employee_LastName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Employee_FirstName {
            get {
                return ResourceManager.GetString("Employee_FirstName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employee_FirstName_RequiredMsg {
            get {
                return ResourceManager.GetString("Employee_FirstName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Employee_Title {
            get {
                return ResourceManager.GetString("Employee_Title", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title Of Courtesy.
        /// </summary>
        public static string Employee_TitleOfCourtesy {
            get {
                return ResourceManager.GetString("Employee_TitleOfCourtesy", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Employee_BirthDate {
            get {
                return ResourceManager.GetString("Employee_BirthDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string Employee_HireDate {
            get {
                return ResourceManager.GetString("Employee_HireDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Employee_Address {
            get {
                return ResourceManager.GetString("Employee_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Employee_City {
            get {
                return ResourceManager.GetString("Employee_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Employee_Region {
            get {
                return ResourceManager.GetString("Employee_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Employee_PostalCode {
            get {
                return ResourceManager.GetString("Employee_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Employee_Country {
            get {
                return ResourceManager.GetString("Employee_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Employee_HomePhone {
            get {
                return ResourceManager.GetString("Employee_HomePhone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Employee_Extension {
            get {
                return ResourceManager.GetString("Employee_Extension", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Employee_Photo {
            get {
                return ResourceManager.GetString("Employee_Photo", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Employee_Notes {
            get {
                return ResourceManager.GetString("Employee_Notes", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reports To.
        /// </summary>
        public static string Employee_ReportsTo {
            get {
                return ResourceManager.GetString("Employee_ReportsTo", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Path.
        /// </summary>
        public static string Employee_PhotoPath {
            get {
                return ResourceManager.GetString("Employee_PhotoPath", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to ReportsToEmployee.
        /// </summary>
        public static string Employee_ReportsToEmployee {
            get {
                return ResourceManager.GetString("Employee_ReportsToEmployee", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property.
        /// </summary>
        public static string SysSettingProperty_TypeDisplayName {
            get {
                return ResourceManager.GetString("SysSettingProperty_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SysSettingProperty_Id {
            get {
                return ResourceManager.GetString("SysSettingProperty_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SysSettingProperty_Name {
            get {
                return ResourceManager.GetString("SysSettingProperty_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is managed.
        /// </summary>
        public static string SysSettingProperty_IsManaged {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsManaged", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsManaged_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsManaged_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SysSettingProperty_Description {
            get {
                return ResourceManager.GetString("SysSettingProperty_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ui editor type.
        /// </summary>
        public static string SysSettingProperty_UIEditorType {
            get {
                return ResourceManager.GetString("SysSettingProperty_UIEditorType", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string SysSettingProperty_GroupName {
            get {
                return ResourceManager.GetString("SysSettingProperty_GroupName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Is overridable.
        /// </summary>
        public static string SysSettingProperty_IsOverridable {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsOverridable", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsOverridable_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsOverridable_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Default type.
        /// </summary>
        public static string SysSettingProperty_DefaultType {
            get {
                return ResourceManager.GetString("SysSettingProperty_DefaultType", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to V sales by category.
        /// </summary>
        public static string VSalesByCategory_TypeDisplayName {
            get {
                return ResourceManager.GetString("VSalesByCategory_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string VSalesByCategory_Id {
            get {
                return ResourceManager.GetString("VSalesByCategory_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string VSalesByCategory_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("VSalesByCategory_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string VSalesByCategory_CategoryName {
            get {
                return ResourceManager.GetString("VSalesByCategory_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string VSalesByCategory_CategoryName_RequiredMsg {
            get {
                return ResourceManager.GetString("VSalesByCategory_CategoryName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string VSalesByCategory_ProductName {
            get {
                return ResourceManager.GetString("VSalesByCategory_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string VSalesByCategory_ProductName_RequiredMsg {
            get {
                return ResourceManager.GetString("VSalesByCategory_ProductName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sales.
        /// </summary>
        public static string VSalesByCategory_ProductSales {
            get {
                return ResourceManager.GetString("VSalesByCategory_ProductSales", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        public static string Shipper_TypeDisplayName {
            get {
                return ResourceManager.GetString("Shipper_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Shipper_Id {
            get {
                return ResourceManager.GetString("Shipper_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Shipper_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Shipper_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Shipper_CompanyName {
            get {
                return ResourceManager.GetString("Shipper_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Shipper_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Shipper_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Shipper_Phone {
            get {
                return ResourceManager.GetString("Shipper_Phone", resourceCulture);
            }
		}
        
        
    }
}