//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScreenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.WebAPI.Controllers.Properties.ScreenResources", typeof(ScreenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers_DisplayName {
            get {
                return ResourceManager.GetString("Customers_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Customers_qCustomers_CompanyName {
            get {
                return ResourceManager.GetString("Customers_qCustomers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Customers_qCustomers_ContactName {
            get {
                return ResourceManager.GetString("Customers_qCustomers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Customers_qCustomers_ContactTitle {
            get {
                return ResourceManager.GetString("Customers_qCustomers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Customers_qCustomers_Address {
            get {
                return ResourceManager.GetString("Customers_qCustomers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Customers_qCustomers_City {
            get {
                return ResourceManager.GetString("Customers_qCustomers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Customers_qCustomers_Region {
            get {
                return ResourceManager.GetString("Customers_qCustomers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Customers_qCustomers_PostalCode {
            get {
                return ResourceManager.GetString("Customers_qCustomers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Customers_qCustomers_Country {
            get {
                return ResourceManager.GetString("Customers_qCustomers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Customers_qCustomers_Phone {
            get {
                return ResourceManager.GetString("Customers_qCustomers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Customers_qCustomers_Fax {
            get {
                return ResourceManager.GetString("Customers_qCustomers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        public static string Shippers_DisplayName {
            get {
                return ResourceManager.GetString("Shippers_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to ShipperCompanyName.
        /// </summary>
        public static string Shippers_blockRegion1_CompanyName {
            get {
                return ResourceManager.GetString("Shippers_blockRegion1_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Shippers_blockRegion1_Phone {
            get {
                return ResourceManager.GetString("Shippers_blockRegion1_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders_DisplayName {
            get {
                return ResourceManager.GetString("Orders_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order details .
        /// </summary>
        public static string Orders_tabqOrders {
            get {
                return ResourceManager.GetString("Orders_tabqOrders", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order products.
        /// </summary>
        public static string Orders_tabqOrderProducts {
            get {
                return ResourceManager.GetString("Orders_tabqOrderProducts", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper details.
        /// </summary>
        public static string Orders_tabqShippers {
            get {
                return ResourceManager.GetString("Orders_tabqShippers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNumber.
        /// </summary>
        public static string Orders_qOrders_Id {
            get {
                return ResourceManager.GetString("Orders_qOrders_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Orders_qOrders_OrderDate {
            get {
                return ResourceManager.GetString("Orders_qOrders_OrderDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string Orders_qOrders_RequiredDate {
            get {
                return ResourceManager.GetString("Orders_qOrders_RequiredDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Orders_qOrders_ShippedDate {
            get {
                return ResourceManager.GetString("Orders_qOrders_ShippedDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Orders_qOrders_Freight {
            get {
                return ResourceManager.GetString("Orders_qOrders_Freight", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Orders_qOrders_Customers_CompanyName {
            get {
                return ResourceManager.GetString("Orders_qOrders_Customers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Orders_qOrders_EmployeeFullName {
            get {
                return ResourceManager.GetString("Orders_qOrders_EmployeeFullName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        public static string Orders_qOrders_Shippers_CompanyName {
            get {
                return ResourceManager.GetString("Orders_qOrders_Shippers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Orders_blockRegion1_ShipAddress {
            get {
                return ResourceManager.GetString("Orders_blockRegion1_ShipAddress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string Orders_blockRegion1_ShipName {
            get {
                return ResourceManager.GetString("Orders_blockRegion1_ShipName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string Orders_blockRegion1_ShipCity {
            get {
                return ResourceManager.GetString("Orders_blockRegion1_ShipCity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string Orders_blockRegion1_ShipRegion {
            get {
                return ResourceManager.GetString("Orders_blockRegion1_ShipRegion", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string Orders_blockRegion1_ShipPostalCode {
            get {
                return ResourceManager.GetString("Orders_blockRegion1_ShipPostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string Orders_blockRegion1_ShipCountry {
            get {
                return ResourceManager.GetString("Orders_blockRegion1_ShipCountry", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Orders_qOrderProducts_Products_ProductName {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_Products_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Orders_qOrderProducts_UnitPrice {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Orders_qOrderProducts_Quantity {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_Quantity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discount, %.
        /// </summary>
        public static string Orders_qOrderProducts_Discount {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_Discount", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to ShipperCompanyName.
        /// </summary>
        public static string Orders_ShipperDetailRegion_CompanyName {
            get {
                return ResourceManager.GetString("Orders_ShipperDetailRegion_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Orders_ShipperDetailRegion_Phone {
            get {
                return ResourceManager.GetString("Orders_ShipperDetailRegion_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to TestDynamicColumns.
        /// </summary>
        public static string TestDynamicColumns_DisplayName {
            get {
                return ResourceManager.GetString("TestDynamicColumns_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories_DisplayName {
            get {
                return ResourceManager.GetString("Categories_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Products.
        /// </summary>
        public static string Categories_tab1 {
            get {
                return ResourceManager.GetString("Categories_tab1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Categories_qCategories_CategoryName {
            get {
                return ResourceManager.GetString("Categories_qCategories_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Categories_qCategories_Description {
            get {
                return ResourceManager.GetString("Categories_qCategories_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Categories_qProducts_ProductName {
            get {
                return ResourceManager.GetString("Categories_qProducts_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string Categories_qProducts_QuantityPerUnit {
            get {
                return ResourceManager.GetString("Categories_qProducts_QuantityPerUnit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Categories_qProducts_UnitPrice {
            get {
                return ResourceManager.GetString("Categories_qProducts_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products_DisplayName {
            get {
                return ResourceManager.GetString("Products_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category details.
        /// </summary>
        public static string Products_tabqCategories {
            get {
                return ResourceManager.GetString("Products_tabqCategories", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier details.
        /// </summary>
        public static string Products_tabqSuppliers {
            get {
                return ResourceManager.GetString("Products_tabqSuppliers", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Products_qProducts_Categories_CategoryName {
            get {
                return ResourceManager.GetString("Products_qProducts_Categories_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Products_qProducts_ProductName {
            get {
                return ResourceManager.GetString("Products_qProducts_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string Products_qProducts_QuantityPerUnit {
            get {
                return ResourceManager.GetString("Products_qProducts_QuantityPerUnit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Products_qProducts_UnitPrice {
            get {
                return ResourceManager.GetString("Products_qProducts_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string Products_qProducts_UnitsInStock {
            get {
                return ResourceManager.GetString("Products_qProducts_UnitsInStock", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string Products_qProducts_UnitsOnOrder {
            get {
                return ResourceManager.GetString("Products_qProducts_UnitsOnOrder", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string Products_qProducts_ReorderLevel {
            get {
                return ResourceManager.GetString("Products_qProducts_ReorderLevel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Products_qProducts_Discontinued {
            get {
                return ResourceManager.GetString("Products_qProducts_Discontinued", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Products_qCategories_CategoryName {
            get {
                return ResourceManager.GetString("Products_qCategories_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Products_qCategories_Description {
            get {
                return ResourceManager.GetString("Products_qCategories_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Products_qSuppliers_CompanyName {
            get {
                return ResourceManager.GetString("Products_qSuppliers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Products_qSuppliers_ContactName {
            get {
                return ResourceManager.GetString("Products_qSuppliers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Products_qSuppliers_ContactTitle {
            get {
                return ResourceManager.GetString("Products_qSuppliers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Products_qSuppliers_Address {
            get {
                return ResourceManager.GetString("Products_qSuppliers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Products_qSuppliers_City {
            get {
                return ResourceManager.GetString("Products_qSuppliers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Products_qSuppliers_Region {
            get {
                return ResourceManager.GetString("Products_qSuppliers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Products_qSuppliers_PostalCode {
            get {
                return ResourceManager.GetString("Products_qSuppliers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Products_qSuppliers_Country {
            get {
                return ResourceManager.GetString("Products_qSuppliers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Products_qSuppliers_Phone {
            get {
                return ResourceManager.GetString("Products_qSuppliers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Products_qSuppliers_Fax {
            get {
                return ResourceManager.GetString("Products_qSuppliers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Products_qSuppliers_HomePage {
            get {
                return ResourceManager.GetString("Products_qSuppliers_HomePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers_DisplayName {
            get {
                return ResourceManager.GetString("Suppliers_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Suppliers_blockRegion1_CompanyName {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Suppliers_blockRegion1_ContactName {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Suppliers_blockRegion1_ContactTitle {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Suppliers_blockRegion1_Address {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Suppliers_blockRegion1_City {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Suppliers_blockRegion1_Region {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Suppliers_blockRegion1_PostalCode {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Suppliers_blockRegion1_Country {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Suppliers_blockRegion1_Phone {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Suppliers_blockRegion1_Fax {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Suppliers_blockRegion1_HomePage {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_HomePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees_DisplayName {
            get {
                return ResourceManager.GetString("Employees_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string Employees_tabqEmployees {
            get {
                return ResourceManager.GetString("Employees_tabqEmployees", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Employees_qEmployees_LastName {
            get {
                return ResourceManager.GetString("Employees_qEmployees_LastName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Employees_qEmployees_FirstName {
            get {
                return ResourceManager.GetString("Employees_qEmployees_FirstName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title Of Courtesy.
        /// </summary>
        public static string Employees_qEmployees_TitleOfCourtesy {
            get {
                return ResourceManager.GetString("Employees_qEmployees_TitleOfCourtesy", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Employees_qEmployees_Title {
            get {
                return ResourceManager.GetString("Employees_qEmployees_Title", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Employees_qEmployees_BirthDate {
            get {
                return ResourceManager.GetString("Employees_qEmployees_BirthDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string Employees_qEmployees_HireDate {
            get {
                return ResourceManager.GetString("Employees_qEmployees_HireDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Employees_qEmployees1_Address {
            get {
                return ResourceManager.GetString("Employees_qEmployees1_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Employees_qEmployees1_City {
            get {
                return ResourceManager.GetString("Employees_qEmployees1_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Employees_qEmployees1_Region {
            get {
                return ResourceManager.GetString("Employees_qEmployees1_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Employees_qEmployees1_PostalCode {
            get {
                return ResourceManager.GetString("Employees_qEmployees1_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Employees_qEmployees1_Country {
            get {
                return ResourceManager.GetString("Employees_qEmployees1_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Employees_qEmployees1_HomePhone {
            get {
                return ResourceManager.GetString("Employees_qEmployees1_HomePhone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Employees_qEmployees1_Notes {
            get {
                return ResourceManager.GetString("Employees_qEmployees1_Notes", resourceCulture);
            }
		}
        
        
    }
}