//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Client.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Client.Contracts.Properties.QueryResources", typeof(QueryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qSuppliers.
        /// </summary>
        public static string qSuppliers_TypeDisplayName {
            get {
                return ResourceManager.GetString("qSuppliers_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string qSuppliers_CompanyName {
            get {
                return ResourceManager.GetString("qSuppliers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string qSuppliers_ContactName {
            get {
                return ResourceManager.GetString("qSuppliers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string qSuppliers_ContactTitle {
            get {
                return ResourceManager.GetString("qSuppliers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string qSuppliers_Address {
            get {
                return ResourceManager.GetString("qSuppliers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string qSuppliers_City {
            get {
                return ResourceManager.GetString("qSuppliers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string qSuppliers_Region {
            get {
                return ResourceManager.GetString("qSuppliers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string qSuppliers_PostalCode {
            get {
                return ResourceManager.GetString("qSuppliers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string qSuppliers_Country {
            get {
                return ResourceManager.GetString("qSuppliers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string qSuppliers_Phone {
            get {
                return ResourceManager.GetString("qSuppliers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string qSuppliers_Fax {
            get {
                return ResourceManager.GetString("qSuppliers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string qSuppliers_HomePage {
            get {
                return ResourceManager.GetString("qSuppliers_HomePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qSuppliers_Id {
            get {
                return ResourceManager.GetString("qSuppliers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to qEmployees.
        /// </summary>
        public static string qEmployees_TypeDisplayName {
            get {
                return ResourceManager.GetString("qEmployees_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qEmployees_Id {
            get {
                return ResourceManager.GetString("qEmployees_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string qEmployees_LastName {
            get {
                return ResourceManager.GetString("qEmployees_LastName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string qEmployees_FirstName {
            get {
                return ResourceManager.GetString("qEmployees_FirstName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string qEmployees_Title {
            get {
                return ResourceManager.GetString("qEmployees_Title", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title Of Courtesy.
        /// </summary>
        public static string qEmployees_TitleOfCourtesy {
            get {
                return ResourceManager.GetString("qEmployees_TitleOfCourtesy", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string qEmployees_BirthDate {
            get {
                return ResourceManager.GetString("qEmployees_BirthDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string qEmployees_HireDate {
            get {
                return ResourceManager.GetString("qEmployees_HireDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string qEmployees_Address {
            get {
                return ResourceManager.GetString("qEmployees_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string qEmployees_City {
            get {
                return ResourceManager.GetString("qEmployees_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string qEmployees_Region {
            get {
                return ResourceManager.GetString("qEmployees_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string qEmployees_PostalCode {
            get {
                return ResourceManager.GetString("qEmployees_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string qEmployees_Country {
            get {
                return ResourceManager.GetString("qEmployees_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string qEmployees_HomePhone {
            get {
                return ResourceManager.GetString("qEmployees_HomePhone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string qEmployees_Extension {
            get {
                return ResourceManager.GetString("qEmployees_Extension", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string qEmployees_Notes {
            get {
                return ResourceManager.GetString("qEmployees_Notes", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reports To.
        /// </summary>
        public static string qEmployees_ReportsTo {
            get {
                return ResourceManager.GetString("qEmployees_ReportsTo", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reports To_FullName.
        /// </summary>
        public static string qEmployees_Employee_FullName {
            get {
                return ResourceManager.GetString("qEmployees_Employee_FullName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to qShippers.
        /// </summary>
        public static string qShippers_TypeDisplayName {
            get {
                return ResourceManager.GetString("qShippers_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qShippers_Id {
            get {
                return ResourceManager.GetString("qShippers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to ShipperCompanyName.
        /// </summary>
        public static string qShippers_CompanyName {
            get {
                return ResourceManager.GetString("qShippers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string qShippers_Phone {
            get {
                return ResourceManager.GetString("qShippers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to qCategories.
        /// </summary>
        public static string qCategories_TypeDisplayName {
            get {
                return ResourceManager.GetString("qCategories_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string qCategories_CategoryName {
            get {
                return ResourceManager.GetString("qCategories_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string qCategories_Description {
            get {
                return ResourceManager.GetString("qCategories_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string qCategories_Picture {
            get {
                return ResourceManager.GetString("qCategories_Picture", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qCategories_Id {
            get {
                return ResourceManager.GetString("qCategories_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to qCustomers.
        /// </summary>
        public static string qCustomers_TypeDisplayName {
            get {
                return ResourceManager.GetString("qCustomers_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qCustomers_Id {
            get {
                return ResourceManager.GetString("qCustomers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string qCustomers_CompanyName {
            get {
                return ResourceManager.GetString("qCustomers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string qCustomers_ContactName {
            get {
                return ResourceManager.GetString("qCustomers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string qCustomers_ContactTitle {
            get {
                return ResourceManager.GetString("qCustomers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string qCustomers_Address {
            get {
                return ResourceManager.GetString("qCustomers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string qCustomers_City {
            get {
                return ResourceManager.GetString("qCustomers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string qCustomers_Region {
            get {
                return ResourceManager.GetString("qCustomers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string qCustomers_PostalCode {
            get {
                return ResourceManager.GetString("qCustomers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string qCustomers_Country {
            get {
                return ResourceManager.GetString("qCustomers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string qCustomers_Phone {
            get {
                return ResourceManager.GetString("qCustomers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string qCustomers_Fax {
            get {
                return ResourceManager.GetString("qCustomers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to qProducts.
        /// </summary>
        public static string qProducts_TypeDisplayName {
            get {
                return ResourceManager.GetString("qProducts_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string qProducts_Id {
            get {
                return ResourceManager.GetString("qProducts_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string qProducts_ProductName {
            get {
                return ResourceManager.GetString("qProducts_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string qProducts_SupplierID {
            get {
                return ResourceManager.GetString("qProducts_SupplierID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string qProducts_CategoryID {
            get {
                return ResourceManager.GetString("qProducts_CategoryID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string qProducts_QuantityPerUnit {
            get {
                return ResourceManager.GetString("qProducts_QuantityPerUnit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string qProducts_UnitPrice {
            get {
                return ResourceManager.GetString("qProducts_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string qProducts_UnitsInStock {
            get {
                return ResourceManager.GetString("qProducts_UnitsInStock", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string qProducts_UnitsOnOrder {
            get {
                return ResourceManager.GetString("qProducts_UnitsOnOrder", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string qProducts_ReorderLevel {
            get {
                return ResourceManager.GetString("qProducts_ReorderLevel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string qProducts_Discontinued {
            get {
                return ResourceManager.GetString("qProducts_Discontinued", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qProducts_Categories_Id {
            get {
                return ResourceManager.GetString("qProducts_Categories_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string qProducts_Categories_CategoryName {
            get {
                return ResourceManager.GetString("qProducts_Categories_CategoryName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string qProducts_Categories_Description {
            get {
                return ResourceManager.GetString("qProducts_Categories_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qProducts_Suppliers_Id {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string qProducts_Suppliers_CompanyName {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string qProducts_Suppliers_ContactName {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string qProducts_Suppliers_ContactTitle {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string qProducts_Suppliers_Address {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string qProducts_Suppliers_City {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string qProducts_Suppliers_Region {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string qProducts_Suppliers_PostalCode {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string qProducts_Suppliers_Country {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string qProducts_Suppliers_Phone {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string qProducts_Suppliers_Fax {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string qProducts_Suppliers_HomePage {
            get {
                return ResourceManager.GetString("qProducts_Suppliers_HomePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to qOrderProducts.
        /// </summary>
        public static string qOrderProducts_TypeDisplayName {
            get {
                return ResourceManager.GetString("qOrderProducts_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qOrderProducts_Id {
            get {
                return ResourceManager.GetString("qOrderProducts_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID.
        /// </summary>
        public static string qOrderProducts_OrderID {
            get {
                return ResourceManager.GetString("qOrderProducts_OrderID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string qOrderProducts_ProductID {
            get {
                return ResourceManager.GetString("qOrderProducts_ProductID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string qOrderProducts_UnitPrice {
            get {
                return ResourceManager.GetString("qOrderProducts_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string qOrderProducts_Quantity {
            get {
                return ResourceManager.GetString("qOrderProducts_Quantity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discount, %.
        /// </summary>
        public static string qOrderProducts_Discount {
            get {
                return ResourceManager.GetString("qOrderProducts_Discount", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string qOrderProducts_Orders_Id {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Company Name.
        /// </summary>
        public static string qOrderProducts_Orders_CustomerID {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_CustomerID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string qOrderProducts_Orders_EmployeeID {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_EmployeeID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string qOrderProducts_Orders_OrderDate {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_OrderDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string qOrderProducts_Orders_RequiredDate {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_RequiredDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string qOrderProducts_Orders_ShippedDate {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShippedDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Company Name.
        /// </summary>
        public static string qOrderProducts_Orders_ShipVia {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShipVia", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string qOrderProducts_Orders_Freight {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_Freight", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string qOrderProducts_Orders_ShipName {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShipName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string qOrderProducts_Orders_ShipAddress {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShipAddress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string qOrderProducts_Orders_ShipCity {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShipCity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string qOrderProducts_Orders_ShipRegion {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShipRegion", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string qOrderProducts_Orders_ShipPostalCode {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShipPostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string qOrderProducts_Orders_ShipCountry {
            get {
                return ResourceManager.GetString("qOrderProducts_Orders_ShipCountry", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string qOrderProducts_Products_Id {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string qOrderProducts_Products_ProductName {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_ProductName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string qOrderProducts_Products_SupplierID {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_SupplierID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string qOrderProducts_Products_CategoryID {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_CategoryID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string qOrderProducts_Products_QuantityPerUnit {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_QuantityPerUnit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string qOrderProducts_Products_UnitPrice {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_UnitPrice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string qOrderProducts_Products_UnitsInStock {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_UnitsInStock", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string qOrderProducts_Products_UnitsOnOrder {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_UnitsOnOrder", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string qOrderProducts_Products_ReorderLevel {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_ReorderLevel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string qOrderProducts_Products_Discontinued {
            get {
                return ResourceManager.GetString("qOrderProducts_Products_Discontinued", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to qOrders.
        /// </summary>
        public static string qOrders_TypeDisplayName {
            get {
                return ResourceManager.GetString("qOrders_TypeDisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNumber.
        /// </summary>
        public static string qOrders_Id {
            get {
                return ResourceManager.GetString("qOrders_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Company Name.
        /// </summary>
        public static string qOrders_CustomerID {
            get {
                return ResourceManager.GetString("qOrders_CustomerID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string qOrders_EmployeeID {
            get {
                return ResourceManager.GetString("qOrders_EmployeeID", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string qOrders_OrderDate {
            get {
                return ResourceManager.GetString("qOrders_OrderDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string qOrders_RequiredDate {
            get {
                return ResourceManager.GetString("qOrders_RequiredDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string qOrders_ShippedDate {
            get {
                return ResourceManager.GetString("qOrders_ShippedDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Company Name.
        /// </summary>
        public static string qOrders_ShipVia {
            get {
                return ResourceManager.GetString("qOrders_ShipVia", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string qOrders_Freight {
            get {
                return ResourceManager.GetString("qOrders_Freight", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string qOrders_ShipName {
            get {
                return ResourceManager.GetString("qOrders_ShipName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string qOrders_ShipAddress {
            get {
                return ResourceManager.GetString("qOrders_ShipAddress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string qOrders_ShipCity {
            get {
                return ResourceManager.GetString("qOrders_ShipCity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string qOrders_ShipRegion {
            get {
                return ResourceManager.GetString("qOrders_ShipRegion", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string qOrders_ShipPostalCode {
            get {
                return ResourceManager.GetString("qOrders_ShipPostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string qOrders_ShipCountry {
            get {
                return ResourceManager.GetString("qOrders_ShipCountry", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qOrders_Customers_Id {
            get {
                return ResourceManager.GetString("qOrders_Customers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string qOrders_Customers_CompanyName {
            get {
                return ResourceManager.GetString("qOrders_Customers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string qOrders_Customers_ContactName {
            get {
                return ResourceManager.GetString("qOrders_Customers_ContactName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string qOrders_Customers_ContactTitle {
            get {
                return ResourceManager.GetString("qOrders_Customers_ContactTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string qOrders_Customers_Address {
            get {
                return ResourceManager.GetString("qOrders_Customers_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string qOrders_Customers_City {
            get {
                return ResourceManager.GetString("qOrders_Customers_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string qOrders_Customers_Region {
            get {
                return ResourceManager.GetString("qOrders_Customers_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string qOrders_Customers_PostalCode {
            get {
                return ResourceManager.GetString("qOrders_Customers_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string qOrders_Customers_Country {
            get {
                return ResourceManager.GetString("qOrders_Customers_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string qOrders_Customers_Phone {
            get {
                return ResourceManager.GetString("qOrders_Customers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string qOrders_Customers_Fax {
            get {
                return ResourceManager.GetString("qOrders_Customers_Fax", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qOrders_Employees_Id {
            get {
                return ResourceManager.GetString("qOrders_Employees_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string qOrders_Employees_LastName {
            get {
                return ResourceManager.GetString("qOrders_Employees_LastName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string qOrders_Employees_FirstName {
            get {
                return ResourceManager.GetString("qOrders_Employees_FirstName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string qOrders_Employees_Title {
            get {
                return ResourceManager.GetString("qOrders_Employees_Title", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title Of Courtesy.
        /// </summary>
        public static string qOrders_Employees_TitleOfCourtesy {
            get {
                return ResourceManager.GetString("qOrders_Employees_TitleOfCourtesy", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string qOrders_Employees_BirthDate {
            get {
                return ResourceManager.GetString("qOrders_Employees_BirthDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string qOrders_Employees_HireDate {
            get {
                return ResourceManager.GetString("qOrders_Employees_HireDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string qOrders_Employees_Address {
            get {
                return ResourceManager.GetString("qOrders_Employees_Address", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string qOrders_Employees_City {
            get {
                return ResourceManager.GetString("qOrders_Employees_City", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string qOrders_Employees_Region {
            get {
                return ResourceManager.GetString("qOrders_Employees_Region", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string qOrders_Employees_PostalCode {
            get {
                return ResourceManager.GetString("qOrders_Employees_PostalCode", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string qOrders_Employees_Country {
            get {
                return ResourceManager.GetString("qOrders_Employees_Country", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string qOrders_Employees_HomePhone {
            get {
                return ResourceManager.GetString("qOrders_Employees_HomePhone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string qOrders_Employees_Extension {
            get {
                return ResourceManager.GetString("qOrders_Employees_Extension", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string qOrders_Employees_Notes {
            get {
                return ResourceManager.GetString("qOrders_Employees_Notes", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reports To.
        /// </summary>
        public static string qOrders_Employees_ReportsTo {
            get {
                return ResourceManager.GetString("qOrders_Employees_ReportsTo", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Path.
        /// </summary>
        public static string qOrders_Employees_PhotoPath {
            get {
                return ResourceManager.GetString("qOrders_Employees_PhotoPath", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string qOrders_Shippers_Id {
            get {
                return ResourceManager.GetString("qOrders_Shippers_Id", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        public static string qOrders_Shippers_CompanyName {
            get {
                return ResourceManager.GetString("qOrders_Shippers_CompanyName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string qOrders_Shippers_Phone {
            get {
                return ResourceManager.GetString("qOrders_Shippers_Phone", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string qOrders_EmployeeFullName {
            get {
                return ResourceManager.GetString("qOrders_EmployeeFullName", resourceCulture);
            }
		}
        
        
    }
}