//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.WebAPI.Controllers.Properties.ActionsResources", typeof(ActionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Customers_qCustomers_WizardCreateNew {
            get {
                return ResourceManager.GetString("Customers_qCustomers_WizardCreateNew", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Customers_qCustomers_WizardView {
            get {
                return ResourceManager.GetString("Customers_qCustomers_WizardView", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Customers_qCustomers_WizardEdit {
            get {
                return ResourceManager.GetString("Customers_qCustomers_WizardEdit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Customers_qCustomers_DeleteEntity {
            get {
                return ResourceManager.GetString("Customers_qCustomers_DeleteEntity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Customers_qCustomers_Refresh {
            get {
                return ResourceManager.GetString("Customers_qCustomers_Refresh", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Shippers_blockRegion1_CreateNew1 {
            get {
                return ResourceManager.GetString("Shippers_blockRegion1_CreateNew1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Shippers_blockRegion1_ActionView1 {
            get {
                return ResourceManager.GetString("Shippers_blockRegion1_ActionView1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Shippers_blockRegion1_Edit1 {
            get {
                return ResourceManager.GetString("Shippers_blockRegion1_Edit1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Shippers_blockRegion1_Delete1 {
            get {
                return ResourceManager.GetString("Shippers_blockRegion1_Delete1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Shippers_blockRegion1_Refresh1 {
            get {
                return ResourceManager.GetString("Shippers_blockRegion1_Refresh1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Orders_qOrders_CreateNew1 {
            get {
                return ResourceManager.GetString("Orders_qOrders_CreateNew1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Orders_qOrders_ActionView1 {
            get {
                return ResourceManager.GetString("Orders_qOrders_ActionView1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Orders_qOrders_Edit1MyButton {
            get {
                return ResourceManager.GetString("Orders_qOrders_Edit1MyButton", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Orders_qOrders_Delete1 {
            get {
                return ResourceManager.GetString("Orders_qOrders_Delete1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Print Invoice.
        /// </summary>
        public static string Orders_qOrders_PrintOrderInvoice {
            get {
                return ResourceManager.GetString("Orders_qOrders_PrintOrderInvoice", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Report.
        /// </summary>
        public static string Orders_qOrders_ClientPrintWithWizardAction {
            get {
                return ResourceManager.GetString("Orders_qOrders_ClientPrintWithWizardAction", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Orders_qOrders_Refresh1 {
            get {
                return ResourceManager.GetString("Orders_qOrders_Refresh1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Orders_qOrderProducts_CreateNew1 {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_CreateNew1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Orders_qOrderProducts_ActionView1 {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_ActionView1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Orders_qOrderProducts_Edit1 {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_Edit1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Orders_qOrderProducts_Delete1 {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_Delete1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Orders_qOrderProducts_Refresh1 {
            get {
                return ResourceManager.GetString("Orders_qOrderProducts_Refresh1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Categories_qCategories_CreateNew1 {
            get {
                return ResourceManager.GetString("Categories_qCategories_CreateNew1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Categories_qCategories_ActionView1 {
            get {
                return ResourceManager.GetString("Categories_qCategories_ActionView1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Categories_qCategories_Edit1 {
            get {
                return ResourceManager.GetString("Categories_qCategories_Edit1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Categories_qCategories_Delete1 {
            get {
                return ResourceManager.GetString("Categories_qCategories_Delete1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Categories_qCategories_Refresh1 {
            get {
                return ResourceManager.GetString("Categories_qCategories_Refresh1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Open report.
        /// </summary>
        public static string Categories_qCategories_OpenReports1 {
            get {
                return ResourceManager.GetString("Categories_qCategories_OpenReports1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Categories_qProducts_CreateNew1 {
            get {
                return ResourceManager.GetString("Categories_qProducts_CreateNew1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Categories_qProducts_ActionView1 {
            get {
                return ResourceManager.GetString("Categories_qProducts_ActionView1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Categories_qProducts_Edit1 {
            get {
                return ResourceManager.GetString("Categories_qProducts_Edit1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Categories_qProducts_Delete1 {
            get {
                return ResourceManager.GetString("Categories_qProducts_Delete1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Categories_qProducts_Refresh1 {
            get {
                return ResourceManager.GetString("Categories_qProducts_Refresh1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Products_qProducts_WizardCreateNew {
            get {
                return ResourceManager.GetString("Products_qProducts_WizardCreateNew", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Products_qProducts_WizardView {
            get {
                return ResourceManager.GetString("Products_qProducts_WizardView", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Products_qProducts_WizardEdit {
            get {
                return ResourceManager.GetString("Products_qProducts_WizardEdit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Products_qProducts_DeleteEntity {
            get {
                return ResourceManager.GetString("Products_qProducts_DeleteEntity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Products_qProducts_Refresh {
            get {
                return ResourceManager.GetString("Products_qProducts_Refresh", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Suppliers_blockRegion1_CreateNew1 {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_CreateNew1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Suppliers_blockRegion1_ActionView1 {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_ActionView1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Suppliers_blockRegion1_Edit1 {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Edit1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Suppliers_blockRegion1_Delete1 {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Delete1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Suppliers_blockRegion1_Refresh1 {
            get {
                return ResourceManager.GetString("Suppliers_blockRegion1_Refresh1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Employees_qEmployees_WizardCreateNew {
            get {
                return ResourceManager.GetString("Employees_qEmployees_WizardCreateNew", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Employees_qEmployees_WizardView {
            get {
                return ResourceManager.GetString("Employees_qEmployees_WizardView", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Employees_qEmployees_WizardEdit {
            get {
                return ResourceManager.GetString("Employees_qEmployees_WizardEdit", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Employees_qEmployees_DeleteEntity {
            get {
                return ResourceManager.GetString("Employees_qEmployees_DeleteEntity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Employees_qEmployees_Refresh {
            get {
                return ResourceManager.GetString("Employees_qEmployees_Refresh", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Region_blockRegion1_ActionView1 {
            get {
                return ResourceManager.GetString("Region_blockRegion1_ActionView1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Region_blockRegion1_CreateNew1 {
            get {
                return ResourceManager.GetString("Region_blockRegion1_CreateNew1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Region_blockRegion1_Edit1 {
            get {
                return ResourceManager.GetString("Region_blockRegion1_Edit1", resourceCulture);
            }
		}
        
        
    }
}