//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.WebAPI.Controllers.Properties.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserPermissionsDisplayView_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserPermissionsDisplayView_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserPermissionsDisplayView_PermissionId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserPermissionsDisplayView_PermissionId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_UserID_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_UserID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_Date_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_Date_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_ActionId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_ActionId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_OperationResultId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_OperationResultId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_ParentId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_ParentId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_ClassId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_ClassId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_Guid_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_Guid_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationResult_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationResult_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationResult_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationResult_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Product_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Product_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Product_ProductName_RequiredMsg {
            get {
                return ResourceManager.GetString("Product_ProductName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Product_Discontinued_RequiredMsg {
            get {
                return ResourceManager.GetString("Product_Discontinued_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Token_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Token_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_ValidFrom_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_ValidFrom_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_IsExecuted_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_IsExecuted_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_ClientId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_ClientId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_Token_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_Token_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_ExpiresUtc_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_ExpiresUtc_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsOwnByUser_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsOwnByUser_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsSystem_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsSystem_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_AccountName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_AccountName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsDeactivated_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsDeactivated_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsSystemUser_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsSystemUser_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_FullAccess_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_FullAccess_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsEmailConfirmed_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsEmailConfirmed_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsAnonymous_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsAnonymous_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_CreateDate_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_CreateDate_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRolePermission_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRolePermission_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRolePermission_RoleId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRolePermission_RoleId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRolePermission_PermissionId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRolePermission_PermissionId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Customer_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Customer_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Customer_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Customer_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Category_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Category_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Category_CategoryName_RequiredMsg {
            get {
                return ResourceManager.GetString("Category_CategoryName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Supplier_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Supplier_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Supplier_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Supplier_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationContext_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationContext_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_AquiredTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_AquiredTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_ExpirationTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_ExpirationTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserRole_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserRole_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserRole_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserRole_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserRole_RoleId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserRole_RoleId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Order_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Order_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_Type_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_Type_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_ObjectId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_ObjectId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_Guid_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_Guid_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_OrderID_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_OrderID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_ProductID_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_ProductID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_UnitPrice_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_UnitPrice_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_Quantity_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_Quantity_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string OrderDetail_Discount_RequiredMsg {
            get {
                return ResourceManager.GetString("OrderDetail_Discount_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_SettingPropertyId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_SettingPropertyId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysInfo_SystemVersion_RequiredMsg {
            get {
                return ResourceManager.GetString("SysInfo_SystemVersion_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysInfo_DomainVersion_RequiredMsg {
            get {
                return ResourceManager.GetString("SysInfo_DomainVersion_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysInfo_LastInitialization_RequiredMsg {
            get {
                return ResourceManager.GetString("SysInfo_LastInitialization_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employee_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Employee_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employee_LastName_RequiredMsg {
            get {
                return ResourceManager.GetString("Employee_LastName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Employee_FirstName_RequiredMsg {
            get {
                return ResourceManager.GetString("Employee_FirstName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectType_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectType_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectType_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectType_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectClass_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectClass_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectClass_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectClass_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectClass_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectClass_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermissionType_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermissionType_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermissionType_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermissionType_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermissionType_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermissionType_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsManaged_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsManaged_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsOverridable_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsOverridable_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUsersDisplayView_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUsersDisplayView_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string VSalesByCategory_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("VSalesByCategory_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string VSalesByCategory_CategoryName_RequiredMsg {
            get {
                return ResourceManager.GetString("VSalesByCategory_CategoryName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string VSalesByCategory_ProductName_RequiredMsg {
            get {
                return ResourceManager.GetString("VSalesByCategory_ProductName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Shipper_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Shipper_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Shipper_CompanyName_RequiredMsg {
            get {
                return ResourceManager.GetString("Shipper_CompanyName_RequiredMsg", resourceCulture);
            }
		}
        
        
    }
}