//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WizardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WizardResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.WebAPI.Controllers.Properties.WizardResources", typeof(WizardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details .
        /// </summary>
        public static string ProductsWizard_Page1 {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add product details.
        /// </summary>
        public static string ProductsWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details .
        /// </summary>
        public static string ProductsWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductsWizard_Page1_ProductName_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_ProductName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ProductsWizard_Page1_CategoryID_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_CategoryID_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string ProductsWizard_Page1_QuantityPerUnit_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_QuantityPerUnit_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string ProductsWizard_Page1_UnitPrice_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_UnitPrice_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string ProductsWizard_Page1_UnitsInStock_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_UnitsInStock_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string ProductsWizard_Page1_UnitsOnOrder_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_UnitsOnOrder_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string ProductsWizard_Page1_ReorderLevel_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_ReorderLevel_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string ProductsWizard_Page1_Discontinued_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_Discontinued_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string ProductsWizard_Page1_SupplierID_DisplayName {
            get {
                return ResourceManager.GetString("ProductsWizard_Page1_SupplierID_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Main Info.
        /// </summary>
        public static string CustomersWizard_Page1 {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add customer main info.
        /// </summary>
        public static string CustomersWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Main Info.
        /// </summary>
        public static string CustomersWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CustomersWizard_Page1_CompanyName_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1_CompanyName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string CustomersWizard_Page1_ContactName_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1_ContactName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string CustomersWizard_Page1_ContactTitle_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1_ContactTitle_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string CustomersWizard_Page1_Phone_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1_Phone_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string CustomersWizard_Page1_Fax_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page1_Fax_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CustomersWizard_Page2 {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add customer address.
        /// </summary>
        public static string CustomersWizard_Page2_BannerTitle {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string CustomersWizard_Page2_BannerDescription {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CustomersWizard_Page2_Address_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2_Address_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CustomersWizard_Page2_City_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2_City_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string CustomersWizard_Page2_Region_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2_Region_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string CustomersWizard_Page2_PostalCode_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2_PostalCode_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CustomersWizard_Page2_Country_DisplayName {
            get {
                return ResourceManager.GetString("CustomersWizard_Page2_Country_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Main Info.
        /// </summary>
        public static string EmployeesWizard_Page1 {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add empolyee main info.
        /// </summary>
        public static string EmployeesWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Main Info.
        /// </summary>
        public static string EmployeesWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string EmployeesWizard_Page1_LastName_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_LastName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string EmployeesWizard_Page1_FirstName_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_FirstName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EmployeesWizard_Page1_Title_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_Title_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Title Of Courtesy.
        /// </summary>
        public static string EmployeesWizard_Page1_TitleOfCourtesy_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_TitleOfCourtesy_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string EmployeesWizard_Page1_BirthDate_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_BirthDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string EmployeesWizard_Page1_HireDate_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_HireDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string EmployeesWizard_Page1_Photo_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_Photo_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string EmployeesWizard_Page1_Notes_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page1_Notes_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string EmployeesWizard_Page2 {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add employee address.
        /// </summary>
        public static string EmployeesWizard_Page2_BannerTitle {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Address.
        /// </summary>
        public static string EmployeesWizard_Page2_BannerDescription {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string EmployeesWizard_Page2_Address_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_Address_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string EmployeesWizard_Page2_City_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_City_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string EmployeesWizard_Page2_Region_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_Region_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string EmployeesWizard_Page2_PostalCode_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_PostalCode_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string EmployeesWizard_Page2_Country_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_Country_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string EmployeesWizard_Page2_HomePhone_DisplayName {
            get {
                return ResourceManager.GetString("EmployeesWizard_Page2_HomePhone_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Page -1.
        /// </summary>
        public static string ShippersWizard_Page1 {
            get {
                return ResourceManager.GetString("ShippersWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add shipper details.
        /// </summary>
        public static string ShippersWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("ShippersWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Details.
        /// </summary>
        public static string ShippersWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("ShippersWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string ShippersWizard_Page1_CompanyName_DisplayName {
            get {
                return ResourceManager.GetString("ShippersWizard_Page1_CompanyName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ShippersWizard_Page1_Phone_DisplayName {
            get {
                return ResourceManager.GetString("ShippersWizard_Page1_Phone_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Page -1.
        /// </summary>
        public static string OrderDetailsWizard_Page1 {
            get {
                return ResourceManager.GetString("OrderDetailsWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add order product info.
        /// </summary>
        public static string OrderDetailsWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("OrderDetailsWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Product Info.
        /// </summary>
        public static string OrderDetailsWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("OrderDetailsWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string OrderDetailsWizard_Page1_ProductID_DisplayName {
            get {
                return ResourceManager.GetString("OrderDetailsWizard_Page1_ProductID_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string OrderDetailsWizard_Page1_UnitPrice_DisplayName {
            get {
                return ResourceManager.GetString("OrderDetailsWizard_Page1_UnitPrice_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderDetailsWizard_Page1_Quantity_DisplayName {
            get {
                return ResourceManager.GetString("OrderDetailsWizard_Page1_Quantity_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Discount, %.
        /// </summary>
        public static string OrderDetailsWizard_Page1_Discount_DisplayName {
            get {
                return ResourceManager.GetString("OrderDetailsWizard_Page1_Discount_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string OrdersWizard_Page1 {
            get {
                return ResourceManager.GetString("OrdersWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add order details.
        /// </summary>
        public static string OrdersWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("OrdersWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string OrdersWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("OrdersWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrdersWizard_Page1_OrderDate_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page1_OrderDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Company Name.
        /// </summary>
        public static string OrdersWizard_Page1_CustomerID_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page1_CustomerID_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string OrdersWizard_Page1_EmployeeID_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page1_EmployeeID_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string OrdersWizard_Page1_RequiredDate_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page1_RequiredDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Shipping Info.
        /// </summary>
        public static string OrdersWizard_Page2 {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add order shipping info.
        /// </summary>
        public static string OrdersWizard_Page2_BannerTitle {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Order Shipping Info.
        /// </summary>
        public static string OrdersWizard_Page2_BannerDescription {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Company Name.
        /// </summary>
        public static string OrdersWizard_Page2_ShipVia_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShipVia_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string OrdersWizard_Page2_ShippedDate_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShippedDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string OrdersWizard_Page2_Freight_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_Freight_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string OrdersWizard_Page2_ShipName_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShipName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string OrdersWizard_Page2_ShipAddress_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShipAddress_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string OrdersWizard_Page2_ShipCity_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShipCity_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string OrdersWizard_Page2_ShipRegion_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShipRegion_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string OrdersWizard_Page2_ShipPostalCode_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShipPostalCode_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string OrdersWizard_Page2_ShipCountry_DisplayName {
            get {
                return ResourceManager.GetString("OrdersWizard_Page2_ShipCountry_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string CategoriesWizard_Page1 {
            get {
                return ResourceManager.GetString("CategoriesWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add category details .
        /// </summary>
        public static string CategoriesWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("CategoriesWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string CategoriesWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("CategoriesWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoriesWizard_Page1_CategoryName_DisplayName {
            get {
                return ResourceManager.GetString("CategoriesWizard_Page1_CategoryName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CategoriesWizard_Page1_Description_DisplayName {
            get {
                return ResourceManager.GetString("CategoriesWizard_Page1_Description_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string CategoriesWizard_Page1_Picture_DisplayName {
            get {
                return ResourceManager.GetString("CategoriesWizard_Page1_Picture_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Details.
        /// </summary>
        public static string SuppliersWizard_Page1 {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page1", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add supplier details.
        /// </summary>
        public static string SuppliersWizard_Page1_BannerTitle {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page1_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Details.
        /// </summary>
        public static string SuppliersWizard_Page1_BannerDescription {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page1_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string SuppliersWizard_Page1_CompanyName_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page1_CompanyName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string SuppliersWizard_Page1_ContactName_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page1_ContactName_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string SuppliersWizard_Page1_ContactTitle_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page1_ContactTitle_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Details.
        /// </summary>
        public static string SuppliersWizard_Page2 {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Please add supplier details.
        /// </summary>
        public static string SuppliersWizard_Page2_BannerTitle {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Details.
        /// </summary>
        public static string SuppliersWizard_Page2_BannerDescription {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SuppliersWizard_Page2_Address_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_Address_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string SuppliersWizard_Page2_City_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_City_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string SuppliersWizard_Page2_Country_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_Country_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string SuppliersWizard_Page2_Fax_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_Fax_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string SuppliersWizard_Page2_HomePage_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_HomePage_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string SuppliersWizard_Page2_Phone_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_Phone_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string SuppliersWizard_Page2_PostalCode_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_PostalCode_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string SuppliersWizard_Page2_Region_DisplayName {
            get {
                return ResourceManager.GetString("SuppliersWizard_Page2_Region_DisplayName", resourceCulture);
            }
		}
        
        
    }
}